<html>
<head>
</head>
	<body>
		This is an autogenerated notification. <br/>
		Channel Number: <?php  echo $model->number; ?> on <?php echo $model->cycler->name; ?> was marked as '<?php echo $commissionStatus; ?>' by  <?php echo $user?>.<br/><br/>
		
<?php if ($_SERVER['SERVER_NAME'] == 'localhost'):?>
		Don't worry, Jack, this is just a test on my development database!!!  But if you got this...IT WORKED.
<?php else: ?>
		This message was sent from the ACTIVE DATABASE.
<?php endif;?>
	</body>
</html>
